server:
  port: 8081
spring:
  application:
    name: xtyx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.7.23:3306/wzq01?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: 12345
  redis:
    host: 192.168.7.23
    password: 12345
    port: 6379
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: xtyx.entity # 别名扫描包
logging:
  level:
    xtyx: debug